er try that again, get 0.2 this time

diff --git a/debian/libghc6-cabal-dev.postinst b/debian/libghc6-cabal-dev.postinst
--- a/debian/libghc6-cabal-dev.postinst
+++ b/debian/libghc6-cabal-dev.postinst
@@ -1,6 +1,43 @@
-#!/bin/sh -e
+#! /bin/sh
+# postinst script for missingh
+#
+# see: dh_installdeb(1)
 
-ghc-pkg -g --add-package \
-   < /usr/share/doc/libghc6-cabal-dev/installed-pkg-config
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+#
+
+case "$1" in
+    configure)
+        /usr/lib/ghc-6.2.2/bin/ghc-pkg-6.2.2 -g --add-package \
+                < /usr/share/doc/libghc6-cabal-dev/installed-pkg-config
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
+
+exit 0
+
+
diff --git a/debian/libghc6-cabal-dev.prerm b/debian/libghc6-cabal-dev.prerm
--- a/debian/libghc6-cabal-dev.prerm
+++ b/debian/libghc6-cabal-dev.prerm
@@ -1,7 +1,42 @@
-#!/bin/sh -e
+#! /bin/sh
+# prerm script for missingh
+#
+# see: dh_installdeb(1)
 
-ghc-pkg -r Cabal
-# ditch that ghci library:
-rm /usr/lib/Cabal-0.1/HSCabal-0.1.o
+set -e
+
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
+case "$1" in
+    remove|upgrade|deconfigure)
+        /usr/lib/ghc-6.2.2/bin/ghc-pkg-6.2.2 -r Cabal 
+        rm /usr/lib/haskell-packages/ghc6/lib/Cabal-0.2/HSCabal*.o
+
+#       install-info --quiet --remove /usr/info/missingh.info.gz
+        ;;
+    failed-upgrade)
+        ;;
+    *)
+        echo "prerm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
+
+exit 0
+
+
